void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int find_sqrt(int n, int guess);
int is_prime_number(int n);
int is_prime(int n, int guess);
int is_palindrome(char *s);
int is_alphanum(char c);
int ignore_case(char a, char b);
int check_palindrome(char *s, int start, int end);
